# Site wide configuration

title:            Clinton Boys
locale:           en_AU
url:              

future:
  - true

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: posts/page:num/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site owner
owner:
  name: Clinton Boys
  avatar: bio-photo.jpg
  bio: "Australian data scientist and mathematician, living in Tel Aviv."
  email: clintonboys@icloud.com
  disqus-shortname: 
  twitter: psephologue
  google:
    plus: #username
    analytics: UA-59479340-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: clintonboys
  linkedin: clintonboys
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

plugins: [jekyll-paginate]